### PR TITLE
Add highlighting

### PR DESCRIPTION
**Pull request by pomartin**
Code from https://github.com/alevalv/oz-vscode under GNU 3 LICENSE

### CODE REVIEW

**Comment by layus** [comment]
Oops, seems like I missed this PR.
I would like to ask first if @alevalv is okay with us merging most of his work with just a mention, even if the license somehow permits it.

@alevalv would you like to merge your repository in the official mozart organization ? This plugin provides evaluation of code snippets, but yours has all the other bells and whistles we could wish for.
It would be better to merge the two repos and keep only one plugin on vscode market. Do you want to be the maintainer of this merged plugin ? Do you still care about Mozart/Oz ?

**Comment by alevalv** [comment]
Hi @layus. I'm fine with merging the plugins, yours has the functionality that mine doesn't have and vice versa :smile: . I can also be a maintainer, but I'm not that well versed on the mozart universe so a bit of help is always welcome. I made that plugin so I was able to attend to a course in my university.

Let me know what needs to be done so my plugin can be added/merged to the mozart organization.

**Comment by layus** [comment]
Hi @alevalv,

Thanks for your quick reply. I have reviewed different ways to merge both histories, and I am not too sure about the right one.

The simplest for me would be to suck parts of your code in this repo (like this PR does). That way we would only integrate parts as they are needed, and stick with this more recent version of the plugin.
You would of course get mentioned in the authors and copyright owners. The disadvantage is that you would disappear from the git history.

A more complex way is to make a full merge of the git histories and try to cope with all the strange incompatibilities with the plugin syntax that was used two years ago. We would also need to merge configuration options and remove/refactor similar functionalities.

So, if you agree, I propose to stick with the former process and 
 1. add you a a maintainer/committer/administrator on this repo.
 1. Re-license this plugin to GPLv3;
 2. Copy/paste files and features one by one from your repo.
 2. Add you as an author for the parts that we reuse, and in a top level file still to be created;

_Would that be fine with you ?_

Ultimately, if you deem this plugin good enough, it would also make sense to remove your plugin from the vscode marketplace.

**Comment by alevalv** [comment]
Fine by me, I think my repo is a bit dated and is better to cherry pick the code that works.

After we merge the plugin I'll update my extension to point to this one.

**Comment by layus** [comment]
Deal ! ;-)

**Comment by layus** [comment]
Thanks @pomartin !
v0.0.5 was just released :-)

What about calling this version v1.0.0 ? I am not sure we need much more features. The linter from alevalv was nice, maybe we could re-import that ?

**Comment by layus** [comment]
@alevalv I made most of the changes discussed above. The only issue is that .json files do not allow comments. Please tell me if you are happy with your credits, and if you see more code/features that we could import.

**Pull request merged**
